### ISSUE TITLE
Question about relations

### ISSUE THREAD

**Issue by pwFoo** [foxorm/foxorm#2]
Hi, after looked into lessql, notorm and some other solutions I found foxorm and I really like it and the dynamic database table feature too. Great job!

Is it right, that I can insert or update related data with just the related table name `project` followed by  `_X_` part?
```
F::create('user',[
    'name'=>'test',
    'project_x_'=>[
        (object)[
            'name'=>'myproject'
        ],
        (object)[
            'name'=>'myproject2'
        ],
    ],
]);
```

**Comment by pwFoo** [comment]
Should that work too?
```
$author = new StdClass;
$author->name = "Bob";

$book = new StdClass;
$book->title = "book1";
$book->author_x_ = $author; // create related entry? "_x_" is needed?

$base->create('books', $book); // save book and author entry?
```

And what's about read relations?
```
$base['books']->setUniqTextKey('title');
$book = $base->read('books','book1'); // get book by title
$author = $book->author_x_; // do I have the author object / database entry? Do I need "_x_" appended?
```

**Comment by devthejo** [comment]
The `_x_` part is only needed at write if you want to create a cascade delete constraint. From the doc:

> The _x_ suffix specify that is an exclusive link. When it's an exclusive relation the list are considered to be dependent on their parent row. If it's removed, they will be deleted as well.

Your second is good, but for your first example you have to specify that is a one to many relationship by adding the `_many_` prefix to children table name:

```php
F::create('user',[
    'name'=>'test',
    '_many_project_x_'=>[
        (object)[
            'name'=>'myproject'
        ],
        (object)[
            'name'=>'myproject2'
        ],
    ],
]);
```

**Comment by pwFoo** [comment]
I like the object based syntax from first comment.
So author could also be an array of objects to create related entries?
```
$book->authors = array($author1, $author2,...);
```

**Comment by devthejo** [comment]
It would be $book->_many_author if there is only one book by author. But if you want a many to many relationship, you need an intermediate table which will join author_id and book_id, so you have to do:
```php
$book->_many2many_author = array($author1, $author2,...);
```

**Comment by pwFoo** [comment]
Thanks, I play with some other parts, before I integrate it with foxorm. May take some time. It's just a private fun project.
Looked in some ORMs and the way relations are done. Some need relationship objects (for example [Maphper](https://github.com/Level-2/Maphper)) and others work with function names ([Lessql](https://github.com/morris/lessql/blob/master/doc/guide.md)).

Maphper is a interesting project too, but looks like it does more than just database orm (collection, caching, ...).
Foxorm focuses more on the essentials things (query / manage database, single file usage) and so should much easier to integrate.
FoxORM is the best / smallest / focused ORM I found with dynamic database.

Thanks!
